[training]
total_timesteps=500000
episodes=50
max_jobs=10
; NoneType
max_steps=null
learning_rate=3e-4

[ppo]
gamma=0.99
gae_lambda=0.95
clip_coef=0.2
ent_coef=0.01
vf_coef=0.5
update_epochs=10
num_minibatches=16
max_grad_norm=0.5
kl_target=0.015

[system]
seed=0
output_dir=results
